name: bvs
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - torch==2.4.0
      - torchvision==0.19.0
      - torchio==0.21.0
      - nibabel==5.3.2
      - SimpleITK==2.5.3
      - numpy==1.26.4
      - scipy==1.13.1
      - pandas==2.2.3
      - scikit-image==0.24.0
      - PyYAML==6.0.2
      - tensorboard==2.19.0
      - pytest==8.3.5

